// Code generated by wit-bindgen-go. DO NOT EDIT.

package yanamultiplier

// This file contains wasmimport and wasmexport declarations for "yana:calculator".

//go:wasmexport multiply
//export multiply
func wasmexport_Multiply(a0 uint32, b0 uint32) (result0 uint32) {
	a := (uint32)((uint32)(a0))
	b := (uint32)((uint32)(b0))
	result := Exports.Multiply(a, b)
	result0 = (uint32)(result)
	return
}
