name = "interpreter-component"
language = "tinygo"
type = "component"
version = "0.1.0"

[component]
wit_world = "interpreter-component"
wasm_target = "wasm32-wasip2"
destination = "build/interpreter-component_s.wasm"
