apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: calculator
  annotations:
    description: 'Calculator app'
    wasmcloud.dev/authors: Yana Krasovska
spec:
  components:
    - name: adder-component
      type: component
      properties:
        image: file://./modules/adder/build/adder-component_s.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 1

    - name: subtractor-component
      type: component
      properties:
        image: file://./modules/subtractor/build/subtractor_component_s.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 1

    - name: multiplier-component
      type: component
      properties:
        image: file://./modules/multiplier/build/multiplier-component_s.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 1

    - name: divider-component
      type: component
      properties:
        image: file://./modules/divider/build/divider-component_s.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 1

    - name: interpreter-component
      type: component
      properties:
        image: file://./modules/interpreter/build/interpreter-component_s.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        - type: link
          properties:
            target: adder-component
            namespace: yanacalculator
            package: adder
            interfaces: [adder]
        - type: link
          properties:
            target: subtractor-component
            namespace: yanacalculator
            package: subtractor
            interfaces: [subtractor]
        - type: link
          properties:
            target: multiplier-component
            namespace: yanacalculator
            package: multiplier
            interfaces: [multiplier]
        - type: link
          properties:
            target: divider-component
            namespace: yanacalculator
            package: divider
            interfaces: [divider]

    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.25.0
      traits:
        - type: link
          properties:
            target: interpreter-component
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source_config:
              - name: default-http
                properties:
                  address: 0.0.0.0:8000
